# Generated by Django 4.2.5 on 2023-12-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmed',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
