# Generated by Django 4.2.5 on 2023-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0003_alter_productmed_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmed',
            name='descripcion',
            field=models.TextField(max_length=512),
        ),
    ]
