# Generated by Django 4.2.7 on 2023-12-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0004_alter_productmed_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmed',
            name='farmacia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productmed',
            name='presentacion',
            field=models.CharField(max_length=256),
        ),
    ]
