# Generated by Django 4.2.7 on 2023-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0009_alter_productgas_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgas',
            name='categoria',
            field=models.CharField(choices=[('UNIFORMES', 'Uniformes'), ('COLORANTES', 'Colorantes'), ('HERRAMIENTAS', 'Herramientas'), ('REPOSTERIA', 'Reposteria'), ('ADITIVOS', 'Aditivos'), ('CUCHILLOS', 'Cuchillos'), ('MOLDES', 'Moldes'), ('OTROS', 'otros'), ('', 'Seleccione una categoría')], default='', max_length=50),
        ),
    ]
